- README.md
Updates the documentation to indicate the asm.js roll back support
Documentation of libraries supported environment
> docs: update doc's to indicate asm.js support

- README.md
- SECURITY.md
Adds a security policy for responsible disclosure of vulnerabilities
Allows security researchers to responsibly disclose security bugs and vulnerabilities.
> docs: add Mattr Security policy

- README.md
Adds an inline sample to the root readme
Documentation
> docs: add inline sample

- package.json
- yarn.lock
Updates to use v0.10.0 of [node-bbs-signatures](https://github.com/mattrglobal/node-bbs-signatures/pull/132)
Retarget to use released version of node-bbs-signatures
> build: update to use v0.10.0 of node-bbs-signatures

- README.md
- bench/index.ts
- sample/browser/index.web-sample.js
- sample/ts-node/src/index.ts
Signed-off-by: Peter Somogyvari <peter.metz@unarin.com>
The browse sample is not working at the moment because of the earlier breaking change in the API.
> fix(sample): update references to generateBls12381G2KeyPair

- scripts/install-binaryen.sh
> fix: adds wget install option to install-binaryen.sh script

- scripts/install-binaryen.sh
Updates the binaryen install script
Fix an issue with installing binaryen
> build(binaryen): update install script

- .github/workflows/codeql-analysis.yml
Add github action workflow for newly released [Code Scanning feature](https://github.blog/2020-09-30-code-scanning-is-now-available/). 
This workflow was auto generated by Github.
> build: add codeql scanning

- scripts/install-binaryen.sh
Fixes an issue with the installation of binaryen including pinned the installed version to prevent the ingestion of further breaking changes from the project.
Required for WASM optimization and ASM.js generation
> build(binaryen): fix install script

- .github/workflows/any-pr.yaml
- Cargo.toml
- package.json
- yarn.lock
- Update support in GH pipeline for testing other node environments
- Bump node-bbs-signature dependency
See above
> build: add node > 10 and other os support

- .github/workflows/any-pr.yaml
Testing out executing the tests for WASM and the native node module across different OS hosts.
See above
> build: update gh action supported test execution os

- docs/CONTRIBUTING.md
Add docs detailing how detailed debugging of the WASM module works.
See above
> docs: add details on debugging wasm

- README.md
Amends the readme to reflect the latest release does not support asm.js
As above
As above
> docs: amend readme

- package.json
- sample/browser/package.json
- sample/browser/webpack.config.js
- sample/browser/yarn.lock
- yarn.lock
https://mattrglobal.atlassian.net/browse/DXM-520
> chore: fix sample browser audit issues

- .github/workflows/push-master.yaml
- .github/workflows/push-release.yaml
> chore: update workflows node versions

- sample/ts-node/package.json
- sample/ts-node/yarn.lock
> build(deps): update deps to fix sample ts-node audit issues

- .github/workflows/push-master.yaml
- .github/workflows/push-release.yaml
> build: update npm token in cd workflow

- CHANGELOG.md
- package.json
- yarn.lock
bump dependency node-bbs-signatures to 0.15.0 and release 1.1.0 of bbs-signatures
> chore(release): publish

- .github/workflows/any-pr.yaml
- package.json
This PR adds a dependency license check to be run on every PR.
This PR adds a dependency license check to be run on every PR.
**[contributing](https://github.com/mattrglobal/docs-engineering/blob/master/process/CONTRIBUTING.md)** document.
[TCM-219](https://mattrglobal.atlassian.net/browse/TCM-219)
> chore: add dependency license check

- package.json
- yarn.lock
Bumping:
- @commitlint/cli from 17.0.2 to 17.7.1
- @commitlint/config-conventional from 17.0.2 to 17.7.0
Fixing security vulnerability
> build(deps): bump @commitlint/cli and @commitlint/config-conventional versions

- yarn.lock
> build(deps): bump debug from 4.1.1 to 4.3.4

- package.json
- yarn.lock
Bumps `rollup` from 2.49.0 to 4.22.4
Fix security vulnerability
> build(deps): bump rollup from 2.49.0 to 4.22.4

- sample/browser/package.json
- sample/browser/yarn.lock
Update `webpack-dev-server` from 5.1.0 to 5.2.0
Fix security vulnerabilities
> build(deps): bump webpack-dev-server from 5.1.0 to 5.2.0 on sample/browser
